branches:
  only:
    - master

matrix:
  include:
    - language: cpp
      os:
        - linux
        - osx
      sudo: false
      dist: trusty
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
      install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "clang" ]]; then
          export CC=clang-3.6 CXX=clang++-3.6;
          fi
      script:
        - mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=MinSizeRel
            -DCMAKE_INSTALL_PREFIX=`pwd`/install ..;
          fi
      
    - language: java
      sudo: false
      dist: trusty